version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/src/discord-bot
hooks:
  ApplicationStop:
    - location: scripts/applicationstop
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/applicationstart
      timeout: 300
      runas: root
